# docker-compose.yml




services:
  web:
    build: .
    container_name: jobifyDz_nextjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - jobifyDz_network

  db:
    image: postgres:15-alpine
    container_name: jobifyDz_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "1425:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobifyDz_network

volumes:
  postgres_data:

networks:
  jobifyDz_network:
    driver: bridge